spring.application.name=reestr
key.unspecified=Testing

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/reestr
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server.port=8080
# ????????? ?????????? data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true